// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkmEqbur_wzHWIygmJhrAdPyvCzXke7-g',
    appId: '1:537675524238:web:45a8acbe57152ec24201df',
    messagingSenderId: '537675524238',
    projectId: 'fir-setup-demo-first',
    authDomain: 'fir-setup-demo-first.firebaseapp.com',
    storageBucket: 'fir-setup-demo-first.firebasestorage.app',
    measurementId: 'G-8NRM1Z9WTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3sI8DEdenv63MMU6qOFQGmLJhmk20Zc',
    appId: '1:537675524238:android:34cce07e88a2e5ba4201df',
    messagingSenderId: '537675524238',
    projectId: 'fir-setup-demo-first',
    storageBucket: 'fir-setup-demo-first.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVH416gMIuiH-dnPFZSBjGRjIYSX0ZhqU',
    appId: '1:537675524238:ios:889659862bf32aa04201df',
    messagingSenderId: '537675524238',
    projectId: 'fir-setup-demo-first',
    storageBucket: 'fir-setup-demo-first.firebasestorage.app',
    iosBundleId: 'com.example.adminpanelNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVH416gMIuiH-dnPFZSBjGRjIYSX0ZhqU',
    appId: '1:537675524238:ios:889659862bf32aa04201df',
    messagingSenderId: '537675524238',
    projectId: 'fir-setup-demo-first',
    storageBucket: 'fir-setup-demo-first.firebasestorage.app',
    iosBundleId: 'com.example.adminpanelNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkmEqbur_wzHWIygmJhrAdPyvCzXke7-g',
    appId: '1:537675524238:web:7671b90899672d104201df',
    messagingSenderId: '537675524238',
    projectId: 'fir-setup-demo-first',
    authDomain: 'fir-setup-demo-first.firebaseapp.com',
    storageBucket: 'fir-setup-demo-first.firebasestorage.app',
    measurementId: 'G-7DW6P7BR43',
  );
}
